### ISSUE TITLE
Make releases

### ISSUE THREAD

**Issue by utdrmac** [ascarter/Go-bbpackage#13]
Hi. Can you please make releases for those of us that don't want to bother with the giant/bloated XCode?

**Comment by ascarter** [comment]
Yeah - I’ll start creating and adding releases.

**Comment by utdrmac** [comment]
Been almost 2 years. Any releases?

**Comment by ascarter** [comment]
Ah - sorry - I will work on that this week. It's been on my to-do list forever.

**Comment by utdrmac** [comment]
Well, I was able to make this myself, no issues, other than the change noted in #14 I think I opened this request back when I didn't have xcode installed.

**Comment by ascarter** [comment]
I have a branch I haven't merged (bbedit12) that fixed that. I'll clean everything up and merge it.

**Comment by ascarter** [comment]
Releases are now being created starting with v1.0.0
