### ISSUE TITLE
Go workspace missing

### ISSUE THREAD

**Issue by beatrixada** [ascarter/Go-bbpackage#8]
Whenever I try to use any of the builtin scripts, I get the error "Go workspace missing." I have attempted to traced this back through the shell scripts but can only figure out that _gows_switch() is failing but not why.

**Comment by beatrixada** [comment]
Now I'm getting "Go workspace already set" and nothing has changed. Where should I start off trying to debug this? Is it possible to see the env that BBEdit has for itself?

**Comment by ascarter** [comment]
Sorry for the late response - I'm rewriting the support scripts to handle the Go environment better. The easiest fix is to quit BBEdit then go to the workspace in your terminal and launch BBEdit from there.

**Comment by ascarter** [comment]
Actually - try this again - I refactored the scripts about a month ago.
