### ISSUE TITLE
Install requires homebrew version of ctags, update readme?

### ISSUE THREAD

**Issue by zentrope** [ascarter/Go-bbpackage#9]
I have go, xcode and bbedit installed, but got this with `make install`:

```
mkdir -p ./Go.bbpackage/Contents
cp README.md ./Go.bbpackage/.
cp LICENSE ./Go.bbpackage/.
cp -R ./src/* ./Go.bbpackage/Contents/.
ctags --recurse --extra=+p+q+r --fields=+a+m+n+S --excmd=number --tag-relative=no --sort=no --exclude=.git --exclude="*_test.go" --exclude="**/testdata/**" --exclude="**/internal/**" -f - /usr/local/Cellar/go/1.8.3/libexec/src | grep -v -E '^(\w+[.])?[^A-Z]\w+\s+\S+\s\d+[;]["]\s+[cfimstv]' > ./gostdlib.tags
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
make: *** [Go.bbpackage/Contents/Completion Data/Go/Go Standard Library.tags] Error 1
```

Running this on the `10.12.6 Beta`, Xcode is `Version 8.3.2 (8E2002)` and Go is `go version go1.8.3 darwin/amd64`.

Any suggestions?

**Comment by zentrope** [comment]
I installed the homebrew version of `ctags`

```
 $ brew install ctags
```

and did a make clean install, and it worked. Maybe add that as a dependency on the readme?

**Comment by ascarter** [comment]
The right way to fix this is to use the built-in BBEdit Ctags (which is now a snapshot of [universal ctags](https://ctags.io)). That has support for Go built-in. I have universal ctags installed an overriding BSD ctags on my machine. I'll clean this up.

**Comment by ascarter** [comment]
You should now be able to built without any externally installed ctags. Thanks for the bug report.
